# CHANGE FILENAME TO GET RID OF THE "EXAMPLE" so it becomes: "site_config.yml"
# the ip or hostname used to generate rtmp URLs
rtmp_base: 127.0.0.1
# this is the base url used to generate internal links
base_url: 127.0.0.1:9000

# the url to the nginx servers status page.
# this is used for discovering the running streams
# if you are running the docker-compose setup you don't need to change that.
stat_url : http://nginx-rtmp:18080/stat
# web protocol - used for generating hls and internal links.
# change this to https if you are using https for example via traefik in front of this setup
web_proto: http
